### ISSUE TITLE
Nitpicking is so fun !

### ISSUE THREAD

**Issue by Nodd** [spyder-ide/conda-manager#34]
Here are a few details that could be improved:
- [x] "Updating package index" label should have 3 dots: "Updating package index..."
- No action in Environments and Tools seem to have an effect (note that I only have a root env). Maybe hide them for now ?
- The channels menu is empty, looks like a duplicate for the channels button ? I think i'd prefer keeping the menu rather than the button, since it's used less often than the filters.
- The Channels button should have an arrow at the right like a combobox. Maybe use a qcombobox for the look and change it's clicked event ?
- Inside the channels subwindow the `+` and `-` buttons should be on the bottom left to save space and so that the list is near the Channels button
- It's very slow to start (more than 10 seconds), is it waiting for something at start ?
- I have a traceback in the console, I don't know what action triggered it:

``` python
Traceback (most recent call last):
  File "c:\anaconda\lib\site-packages\conda_manager\api\download_api.py", line 197, in start
    self.sig_finished.emit(self, output, error)
UnboundLocalError: local variable 'error' referenced before assignment
```
- It looks like the proxy is not taken into account (on windows) so I can't update the package list. I get no error, it just loops inifinitely Even the installed packages are not shown. So I can't test it any further...

**Comment by goanpeca** [comment]
Thanks for the testing @nodd, will get back to you after I have fixed the bugs found

**Comment by goanpeca** [comment]
@Nodd The slow start is with nothing appearing on screen. Or tking too much time to load pacakge listing once the window is displayed?

**Comment by Nodd** [comment]
Nothing on screen at all. Maybe it's already trying to update the packages before showing the window, i don't know.
In my case the listing is never shown even after more than an hour while the window apears after 10s or so.

**Comment by goanpeca** [comment]
whaaaaaaaat ?? ? 

Ok something is really not working ok

**Comment by Nodd** [comment]
I created a separate issue for the slow startup.

I tried with last master, it still can't reach the server but at least it lists the installed packages. BTW it displays no error when if the connection can't be made, not good !
 Of course that means that I have a new list of complaints:
- the context menu appears on left click in some columns, and never in the others. What I fell would be more intuitive is that the menu should appear on a right click in any column, and on the left click in the checkbox column only (in addition to the right click)
- There are empty column at the left and at the right. What are they for ?
- "Install specific version" submenu should be disables instead of hidden when there are no other version. It makes the menu more consistent between packages. Note that since I can't connect, I have no package with another version so it might be a side effect here.
- Pressing Esc in the search field should clear the search filter. Maybe add a button too ?
- A click on the channels button should toggle the subwindow, not redisplay it.
- I don't think that the "View by:" label is necessary, it's quite obvious from the combobox only. The line is already quite crowded.
- Is it possible to put the search icon inside the QLineEdit ? The icon by itself is too much disconnected, it looks more like another (flat) button.

**Comment by goanpeca** [comment]
Thanks @Nodd 

> Empty columns and view by icon inside lineedit: 
> *_(aesthetics) *_
> We are using this package in a product to be released soon, I can hide them when running in stand alone mode / spyder plugin mode.
- Channels toggle behavior: Agree, can you open a separate issue for this issue?
- Install specific version: Agree can you open a separate issue for this?
- Context menu clicks: Agree can you open a separate issue for this?
- Pressing escape: Agree can you open a separate issue for this?

**Comment by goanpeca** [comment]
BTW, I guess you have your proxy settings configured on the condarc file?

**Comment by Nodd** [comment]
I created the separate issues.
